services:
  web:
    build: .
    container_name: sankalan_backend
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=trash_tracker_backend.settings
      - DEBUG=1
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - SECURE_SSL_REDIRECT=0
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
