# Generated by Django 5.1.3 on 2024-11-18 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WasteBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('fill_level', models.CharField(choices=[('Empty', 'Empty'), ('Half-Filled', 'Half-Filled'), ('Full', 'Full')], default='Empty', max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Full', 'Full'), ('Collected', 'Collected')], max_length=10)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('waste_bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wastebins.wastebin')),
            ],
        ),
    ]
