# Generated by Django 5.1.3 on 2024-11-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wastebins', '0002_remove_request_location_remove_wastebin_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastebin',
            name='name',
            field=models.CharField(default='Bin', max_length=100),
        ),
    ]
