# Generated by Django 5.1.3 on 2024-11-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wastebins', '0003_wastebin_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('reason', models.TextField()),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
