# Generated by Django 5.1.3 on 2024-11-22 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wastebins', '0004_reportwaste'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportwaste',
            old_name='reason',
            new_name='description',
        ),
    ]
