# Generated by Django 6.0.6 on 2026-06-28 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='google_id',
        ),
    ]
